services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm", "run", "start"]
    container_name: server
    environment:
      - ENV_FILE=envs/.env.pro
      - LOG_PATH=logs/
    volumes:
      - ./envs:/app/envs
      - ./logs:/app/logs
      - ./sqls:/app/sqls
      - ./asst:/app/asst
    ports:
      - "3000:3000"
