
### GET ACCOUNTS
GET http://localhost:3000/accounts/
Accept: application/json
Content-Type: application/json

### CREATE ACCOUNT
POST http://localhost:3000/accounts/signup/
Accept: application/json
Content-Type: application/json

{
    "name": "johnson grimes",
    "email": "johnson@example.com"
}

### FIND ACCOUNT
GET http://localhost:3000/accounts/7671
Accept: application/json
Content-Type: application/json


#### LIVE REQUESTS



### GET ACCOUNTS
GET https://bucket-space-api.onrender.com/accounts/
Accept: application/json
Content-Type: application/json

### CREATE ACCOUNT
POST https://bucket-space-api.onrender.com/accounts/signup/
Accept: application/json
Content-Type: application/json

{
    "name": "johnson grimes",
    "email": "johnson@example.com"

}

### FIND ACCOUNT
GET https://bucket-space-api.onrender.com/accounts/7671/
Accept: application/json
Content-Type: application/json
